### ISSUE TITLE
Attribution, 'from' addresses

### ISSUE THREAD

**Issue by zw** [jashmenn/bitcoin-reading-list#4]
Both of these:
- Signing Offline Transactions (greg)
- 2 of 2 escrow example (greg)

should also be attributed "Maxwell" (or "Greg Maxwell") &mdash; like "Proving Your Bitcoin Reserves" is.

Also, I don't usually bundle issues but this is debatable and probably not really worth an issue in itself: you might find this post on [the non-existence of 'from' addresses](https://iwilcox.me.uk/2014/no-from-address) suitable for the Content list, since the motivation for it is partly encouraging bug-free code and keeping the ecosystem (wallets & services) capable of handling advanced transactions later; there are some words on that in the [short discussion of it](http://redd.it/272ebr).

Edit: whoops, should make it clear: I'm iwilcox, and penned both the 'from address' thing and  (around Greg's idea) the 'Proving Your Bitcoin Reserves' thing.

**Comment by jashmenn** [comment]
This is great feedback. 
1. I fixed the attributions to Maxwell
2. I added a "Discussion" section as I wasn't quite sure where to put the 'From Address' article, but I think it's relevant.  It might get shuffled around as we figure out the best grouping.

In any case, thanks! This is great.
